package com.smartconstruct.backend_core.service.impl;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import net.jqwik.api.*;

import java.lang.reflect.Method;

/**
 * Property 2: 编码实训数据格式一致性
 *
 * <b>Validates: Requirements 1.3</b>
 *
 * For any coding_class node generated by DemoDataSeederService.generateCodingClassContent,
 * the output JSON SHALL contain a "coding_task" object with:
 * - description: string, ≤500 characters
 * - code_template: non-empty string
 * - hints: array with 1-5 elements (each non-empty string)
 * - test_cases: array with 2-10 elements, each with "description", "input", "expected" fields
 * - language: must equal "python"
 *
 * Label format: "Feature: student-training-demo, Property 2: 编码实训数据格式一致性"
 */
class CodingClassContentPropertyTest {

    private static final ObjectMapper objectMapper = new ObjectMapper();
    private static final DemoDataSeederService seederService;

    static {
        try {
            // Create instance with null dependencies (only objectMapper is needed for generateCodingClassContent)
            seederService = new DemoDataSeederService(
                    null, null, null, null, null, null, null, null, null, null, null, objectMapper);
        } catch (Exception e) {
            throw new RuntimeException("Failed to create DemoDataSeederService for testing", e);
        }
    }

    /**
     * Invokes the private generateCodingClassContent method via reflection
     * to test its output format.
     */
    private ObjectNode callGenerateCodingClassContent(String nodeName) {
        try {
            Method method = DemoDataSeederService.class.getDeclaredMethod("generateCodingClassContent", String.class);
            method.setAccessible(true);
            return (ObjectNode) method.invoke(seederService, nodeName);
        } catch (Exception e) {
            throw new RuntimeException("Failed to invoke generateCodingClassContent", e);
        }
    }

    @Provide
    Arbitrary<String> randomNodeNames() {
        Arbitrary<String> topics = Arbitraries.of(
                "二分查找", "冒泡排序", "选择排序", "插入排序", "线性搜索",
                "递归基础", "列表操作", "函数定义", "字符串处理", "栈与队列",
                "Python编码实训", "算法入门练习", "数据结构基础", "循环与迭代", "条件判断练习"
        );
        Arbitrary<String> suffixes = Arbitraries.of(
                "", " - 基础", " - 进阶", " - 练习", " - 实战",
                " (上)", " (下)", " 第1节", " 第2节", " 第3节"
        );
        return Combinators.combine(topics, suffixes).as((topic, suffix) -> topic + suffix);
    }

    @Property(tries = 100)
    @Label("Feature: student-training-demo, Property 2: 编码实训数据格式一致性")
    void codingClassContentHasValidStructure(@ForAll("randomNodeNames") String nodeName) {
        ObjectNode result = callGenerateCodingClassContent(nodeName);

        // Must have "coding_task" object at root
        assert result.has("coding_task") : "Root must contain 'coding_task' field";
        JsonNode codingTask = result.get("coding_task");
        assert codingTask.isObject() : "'coding_task' must be an object";

        // Validate description: string, ≤500 characters
        assert codingTask.has("description") : "coding_task must contain 'description'";
        JsonNode description = codingTask.get("description");
        assert description.isTextual() : "'description' must be a string";
        assert description.asText().length() <= 500 :
                "description must be ≤500 characters, got " + description.asText().length();

        // Validate code_template: non-empty string
        assert codingTask.has("code_template") : "coding_task must contain 'code_template'";
        JsonNode codeTemplate = codingTask.get("code_template");
        assert codeTemplate.isTextual() : "'code_template' must be a string";
        assert !codeTemplate.asText().isEmpty() : "'code_template' must be non-empty";

        // Validate hints: array with 1-5 elements, each non-empty string
        assert codingTask.has("hints") : "coding_task must contain 'hints'";
        JsonNode hints = codingTask.get("hints");
        assert hints.isArray() : "'hints' must be an array";
        int hintsSize = hints.size();
        assert hintsSize >= 1 && hintsSize <= 5 :
                "hints must have 1-5 elements, got " + hintsSize;
        for (int i = 0; i < hintsSize; i++) {
            JsonNode hint = hints.get(i);
            assert hint.isTextual() : "hints[" + i + "] must be a string";
            assert !hint.asText().isEmpty() : "hints[" + i + "] must be non-empty";
        }

        // Validate test_cases: array with 2-10 elements
        assert codingTask.has("test_cases") : "coding_task must contain 'test_cases'";
        JsonNode testCases = codingTask.get("test_cases");
        assert testCases.isArray() : "'test_cases' must be an array";
        int testCasesSize = testCases.size();
        assert testCasesSize >= 2 && testCasesSize <= 10 :
                "test_cases must have 2-10 elements, got " + testCasesSize;
        for (int i = 0; i < testCasesSize; i++) {
            JsonNode tc = testCases.get(i);
            assert tc.isObject() : "test_cases[" + i + "] must be an object";
            assert tc.has("description") : "test_cases[" + i + "] must have 'description'";
            assert tc.get("description").isTextual() : "test_cases[" + i + "].description must be a string";
            assert tc.has("input") : "test_cases[" + i + "] must have 'input'";
            assert tc.get("input").isTextual() : "test_cases[" + i + "].input must be a string";
            assert tc.has("expected") : "test_cases[" + i + "] must have 'expected'";
            assert tc.get("expected").isTextual() : "test_cases[" + i + "].expected must be a string";
        }

        // Validate language: must equal "python"
        assert codingTask.has("language") : "coding_task must contain 'language'";
        JsonNode language = codingTask.get("language");
        assert language.isTextual() : "'language' must be a string";
        assert "python".equals(language.asText()) :
                "language must be 'python', got '" + language.asText() + "'";
    }
}
