from pydantic import BaseModel, Field
from typing import Optional, List
from enum import Enum


class AgentType(str, Enum):
    """Agent types for the multi-agent orchestration system."""

    TEXT = "TEXT_AGENT"
    STRUCT = "STRUCT_AGENT"
    EXAM = "EXAM_AGENT"
    CODE = "CODE_AGENT"
    VIDEO = "VIDEO_AGENT"


class OrchestrationRequest(BaseModel):
    """Request model for submitting a template to the AI orchestration pipeline."""

    template_id: int = Field(description="模板ID", gt=0)
    orchestration_id: str = Field(description="编排唯一标识")
    canvas_json: dict = Field(description="原始画布JSON，包含nodes和edges")
    callback_url: str = Field(description="处理完成后的回调地址")


class OrchestrationResponse(BaseModel):
    """Response model returned immediately after accepting an orchestration request."""

    job_id: str = Field(description="异步任务ID")
    status: str = Field(default="accepted", description="任务状态")
    estimated_duration_seconds: int = Field(description="预估处理时间（秒）")


class AgentTask(BaseModel):
    """A single task to be dispatched to a domain-specific agent."""

    task_id: str = Field(description="任务唯一标识")
    agent_type: AgentType = Field(description="目标Agent类型")
    node_id: str = Field(description="画布节点ID")
    node_type: str = Field(description="节点类型")
    config: dict = Field(description="节点配置")
    context: Optional[dict] = Field(default=None, description="附加上下文信息")


class ExecutionPlan(BaseModel):
    """Parallel execution plan generated by the Supervisor Agent."""

    orchestration_id: str = Field(description="编排唯一标识")
    parallel_jobs: List[AgentTask] = Field(description="可并行执行的任务列表")
    total_tasks: int = Field(description="任务总数")
